import empreintesBotucatu from '../../../../public/assets/images_doc/decouvertes/empreintes_botucatu.jpg';
import YaguarasaurusRegiomontanus from '../../../../public/assets/images_doc/decouvertes/Yaguarasaurus_regiomontanus.jpg';

const decouvertesRecentesData = [
  {
    notion: 'La reproduction des sauropodomorphes',
    explications:
      "Des paléontologues chinois rapportent la découverte de trois squelettes adultes et cinq couvées contenant des embryons d’un nouveau dinosaure du Jurassique inférieur du sud-ouest de la Chine. L’espèce concernée, désormais baptisée 'Qianlong shouhu', vivait il y a environ 200 à 193 millions d’années. Il intégrait le groupe des sauropodomorphes qui comprend les dinosaures herbivores à long cou. <br /><br /> Mesurant environ six mètres de long et pesant environ une tonne, cette créature ancienne offre des informations fascinantes sur la reproduction des sauropodomorphes. <br /><br /> Les fossiles, découverts dans la formation de Ziliujing, dans la province du Guizhou, présentent des caractéristiques intéressantes. Les embryons de Qianlong shouhu révèlent en effet des différences notables par rapport aux adultes, telles qu’un crâne plus long et un museau différent. <br /><br />Des analyses allométriques (méthodes d’analyse statistique qui examinent les relations entre les différentes parties d’un organisme en fonction de leur taille) suggèrent que les adultes étaient bipèdes, tandis que les bébés étaient probablement quadrupèdes. <br /> En ce qui concerne les oeufs, dont la coquille coriace mesurait de 70 à 200 μm, ils étaient relativement gros, avec une coquille calcaire inhabituellement épaisse formée de cônes mamillaires proéminents. Les chercheurs estiment que cette espèce pratiquait probablement la nidification coloniale, un comportement reproducteur similaire à d’autres sauropodomorphes.",
    illustrations: [],
  },
  {
    notion: 'Empreintes du paléodésert de Botucatu',
    explications:
      'La formation de Botucatu est située près de Sao Paulo, au Brésil. Cette formation géologique est réputée pour ses vastes étendues de grès qui ont conservé des empreintes fossiles, notamment celles de dinosaures, de mammifères et d’autres tétrapodes. <br /><br /> Datant du Crétacé inférieur, soit il y a environ 135 millions d’années, cette formation géologique offre un aperçu fascinant de la vie animale de cette époque dans la région. Elle couvrait à l’origine une vaste étendue estimée à au moins 1,3 million de km², formant ainsi le plus grand désert fossile connu de l’histoire de la Terre.<br /><br /> L’étude de ces empreintes fossiles permet aux chercheurs de mieux comprendre la diversité des tétrapodes et les conditions environnementales qui prévalaient dans la région à l’époque du Crétacé inférieur. La découverte récente de nouvelles traces imprimées dans le sol par un petit dinosaure carnivore ajoute ainsi une nouvelle pièce au puzzle de la paléontologie de cette région et de cette période. <br /><br /> Les empreintes laissées par ce dinosaure sont distinctes de toutes les autres traces de théropodes connues. Elles représentent un nouvel ichnogenre (type d’empreinte) et une nouvelle ichnoespèce (espèce identifiée par des empreintes fossiles). L’animal, nommé Farlowichnus rapidus, était un carnivore de petite taille, mesurant environ 1,5 mètre de long. Farlowichnus rapidus possède des caractéristiques uniques, dont un angle de pas très élevé. Il s’agit de l’angle formé par la trajectoire des empreintes de pas par rapport à une ligne médiane imaginaire. Un angle de pas élevé signifie que les empreintes sont inclinées par rapport à cette ligne médiane. Les chercheurs ont également relevé des foulées longues. Autrement dit, ce dinosaure se déplaçait avec de grandes enjambées entre chaque pas.<br /><br /> Enfin, l’examen de ces empreintes a permis de relever une largeur de voie interne et externe très étroite. Notez que la voie fait référence à la distance latérale entre les empreintes gauche et droite. Une largeur de voie étroite signifie que les empreintes du dinosaure étaient rapprochées, que ce soit du côté interne (plus proche de la ligne médiane) ou externe (plus éloignée de la ligne médiane).<br /><br /> Les empreintes sont également presque parallèles ou légèrement divergentes par rapport à la ligne médiane et aucune marque de queue ou traînée n’est visible.<br /><br /> Autrement dit, ces caractéristiques suggèrent que Farlowichnus rapidus était un dinosaure rapide qui se déplaçait avec des pas presque parallèles, couvrant de grandes distances à chaque foulée, et dont les empreintes étaient rapprochées latéralement. Ces détails aident les chercheurs à reconstruire le comportement et la locomotion de l’animal dans son environnement préhistorique.',
    illustrations: [empreintesBotucatu],
  },
  {
    notion: 'Mosasaure à langue fourchue',
    explications:
      "En 2021, la découverte exceptionnelle d'un fossile de mosasaure au Mexique, datant de 90 millions d'années, ouvre une nouvelle perspective sur la compréhension des écosystèmes marins du Crétacé. Baptisé Yaguarasaurus regiomontanus, ce mosasaure, découvert dans l'état de Nuevo Leon, se distingue par sa taille imposante, atteignant 5,2 mètres, ce qui en fait l'un des plus grands de son temps. Cette découverte, publiée dans le Journal of South American Earth Sciences, enrichit notre compréhension des schémas évolutifs et de la répartition géographique de ces reptiles marins.<br /><br /> Yaguarasaurus regiomontanus se positionne comme un acteur majeur parmi les mosasaures, groupe de reptiles marins, et sa taille lui conférait un avantage significatif dans son habitat, lui permettant de dominer les chaînes alimentaires marines. L'analyse du fossile, centrée autour d'un crâne presque complet, révèle des caractéristiques anatomiques uniques, notamment une langue fourchue, une adaptation rare chez les mosasaures et plus courante chez les serpents et lézards modernes. Cette langue suggère des adaptations spécifiques pour la chasse ou la perception sensorielle, améliorant la détection des proies dans les environnements marins complexes du Crétacé.<br /><br /> L'analyse du palais et des dents de Yaguarasaurus regiomontanus indique un régime alimentaire varié adapté à ses capacités de prédateur des océans. Ses dents coniques, similaires à celles d'un requin, étaient efficaces pour saisir et retenir des proies glissantes telles que les poissons. Ces caractéristiques, associées à sa langue fourchue, dessinent le portrait d'un prédateur complexe adapté à son environnement.<br /><br /> Yaguarasaurus regiomontanus, en tant que l'un des premiers grands mosasaures, représente un maillon essentiel dans l'évolution de ces reptiles marins. Sa découverte offre des indices sur les adaptations physiques et comportementales de ces créatures et contribue à la compréhension de leur diversification et expansion rapide au cours du Turonien, une époque marquée par des changements environnementaux et biologiques significatifs. Cette découverte souligne l'importance des facteurs environnementaux et climatiques dans la dispersion et l'évolution des mosasaures, offrant des perspectives précieuses sur les dynamiques écologiques du Crétacé.",
    illustrations: [YaguarasaurusRegiomontanus],
  },
];

export default decouvertesRecentesData;
